name: (CI)

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.FSC-PS/**'
      - 'tests/**'
    branches:
       - main
   
permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
   CI:
    runs-on: [ windows-latest ]
    name: Gated Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Initialize the workflow
        uses: ciellosinc/FSC-PS-Actions/WorkflowInitialize@v1.2
        id: init
        env:
          secrets: ${{ toJson(secrets) }}    

      - name: Read settings
        id: ReadSettings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.2

      - name: Read secrets
        uses: ciellosinc/FSC-PS-Actions/ReadSecrets@v1.2
        env:
          secrets: ${{ toJson(secrets) }}    
        with:
          settingsJson: ${{ env.Settings }}
          
      - name: Check for updates to FSC-PS system files
        uses: ciellosinc/FSC-PS-Actions/CheckForUpdates@v1.2
        continue-on-error: true
        with:
          type: ${{ steps.ReadSettings.outputs.type }}
          settingsJson: ${{ env.Settings }}
          SecretsJson: ${{ env.RepoSecrets }}
        
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0   
        with:
          node-version: '16'
          
      - name: Run pipeline
        uses: ciellosinc/FSC-PS-Actions/RunPipeline@v1.2
        id: runpipeline
        with:
          type: ${{ steps.ReadSettings.outputs.type }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}
                  
      - name: Finalize the workflow
        id: PostProcess
        uses: ciellosinc/FSC-PS-Actions/WorkflowPostProcess@v1.2
        with:
          remove_current: ${{ steps.ReadSettings.outputs.EnvironmentsJson == '' }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}